name: CI/CD Gitflow

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
      - 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          DOCKER_COMPOSE_VERSION=1.29.2
          sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build and Start Docker Compose
        run: docker-compose -f docker-compose.yml up -d --build

      - name: Wait for Database
        run: |
          until docker-compose exec -T db pg_isready -U postgres; do
            echo "Waiting for database..."
            sleep 5
          done

#      - name: Run Tests
#        run: docker-compose exec app mvn test

      - name: Stop Docker Compose
        run: docker-compose down

      - name: Code Quality Check
        uses: SonarSource/sonarcloud-github-action@v1.7
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=my_project_key
            -Dsonar.organization=my_organization

#      - name: Secret Detection
#        uses: actions/checkout@v2
#                - name: Run TruffleHog
#                run: trufflehog --regex --entropy=False --max_depth=50 https://github.com/owner/repo.git



  merge-feature-to-develop:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' && github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Merge feature into develop
        run: |
          git checkout develop
          git merge --no-ff ${{ github.head_ref }}
          git push origin develop
